version: '3.7'

services:

  nginx:
    build:
      ./environment/docker/nginx
    restart: always
    volumes:
      - ./storage/logs/nginx:/var/log/nginx
      - .:/application
    ports:
      - 80:80
      - 443:443
    links:
      - php
    networks:
      - internal

  php:
    build:
      ./environment/docker/php/7.4
    restart: always
    volumes:
      - .:/application
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - mariadb
    networks:
      - internal

  mariadb:
    build:
      ./environment/docker/mariadb/10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - ./environment/databases/mariadb:/var/lib/mysql
      - ./storage/logs/mariadb:/var/log/mariadb
    ports:
      - 3306:3306
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
