version: '3.7'

services:

  nginx:
    build:
      ./containers/nginx
    restart: always
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src:/application
    ports:
      - 80:80
      - 443:443
    links:
      - php
    networks:
      - internal

  php:
    build:
      ./containers/php/7.4-fpm
    restart: always
    volumes:
      - ./src:/application
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - mariadb
    networks:
      - internal

  mariadb:
    build:
      ./containers/databases/mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - ./databases/mariadb:/var/lib/mysql
      - ./logs/mariadb:/var/log/mariadb
    ports:
      - 3306:3306
    networks:
      - internal

#  adminer:
#    build:
#      ./containers/adminer
#    restart: always
#    ports:
#      - 8000:8080
#    networks:
#      - internal

#  composer:
#    build:
#      ./containers/composer
#    volumes:
#      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
#    working_dir: ${APP_PATH_CONTAINER}
#    command: composer install

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28