version: '3.7'

services:

  nginx:
    build:
      ./containers/nginx
    restart: always
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    ports:
      - 80:80
      - 443:443
    links:
      - php

  php:
    build:
      ./containers/php/7.2-fpm
    restart: always
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    links:
      - mariadb

  node:
    build:
      ./containers/node
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}

  mariadb:
    build:
      ./containers/databases/mariadb
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./databases/mariadb:/var/lib/mysql
      - ./logs/mariadb:/var/log/mariadb

  adminer:
    build:
      ./containers/adminer
    restart: always
    ports:
      - 8000:8080

  composer:
    build:
      ./containers/composer
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install
